version: 2
services:
  - type: web
    name: brasil-burger-client
    runtime: docker
    plan: starter
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: PAYMENT_MODE
        value: test
      - key: WAVE_API_KEY
        sync: false
      - key: WAVE_MERCHANT_ID
        sync: false
      - key: OM_API_KEY
        sync: false
      - key: OM_MERCHANT_ID
        sync: false