parameters:
    app.site_name: 'Brasil Burger'
    cloudinary.cloud_name: '%env(CLOUDINARY_CLOUD_NAME)%'
    cloudinary.base_url: 'https://res.cloudinary.com'
    app.default_currency: '$'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Implémentation Cloudinary
    App\Infrastructure\Images\Impl\CloudinaryImageService:
        arguments:
            $cloudName: '%cloudinary.cloud_name%'
            $baseUrl: '%cloudinary.base_url%'

    App\Infrastructure\Images\ImageStorageInterface: '@App\Infrastructure\Images\Impl\CloudinaryImageService'
