parameters:
    app.site_name: 'Brasil Burger'
    cloudinary.cloud_name: '%env(CLOUDINARY_CLOUD_NAME)%'
    cloudinary.base_url: 'https://res.cloudinary.com'
    app.default_currency: 'F CFA'
    app.pagination.per_page_choices:
        "4": 4
        "8": 8
        "15": 15
        "20": 20
    app.pagination.default_per_page: 4

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Implémentation Cloudinary
    App\Infrastructure\Images\Impl\CloudinaryImageService:
        arguments:
            $cloudName: '%cloudinary.cloud_name%'
            $baseUrl: '%cloudinary.base_url%'

    App\Infrastructure\Images\ImageStorageInterface: '@App\Infrastructure\Images\Impl\CloudinaryImageService'
