security:
    password_hashers:
        App\Entity\Utilisateur:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: login

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            entry_point: form_login
            user_checker: App\Security\GestionnaireUserChecker
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                csrf_parameter: _csrf_token
                csrf_token_id: authenticate
                default_target_path: app_home
            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
